cloud:
  aws:
    s3:
      bucket: minipro-bucket # AWS S3 Bucket Name
    region:
      static: ap-northeast-2 # AWS Region
    stack:
      auto: false
    credentials:
      accessKey: AKIAQFBK5SIWSXTCSW6Z
      secretKey: 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
#cloud:
#  aws:
#    credentials:
#      accessKey: {Accesskey 입력} # AWS IAM AccessKey
#      secretKey: {Secret Key 입력} # AWS IAM SecretKey